/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.views;

import javax.swing.JOptionPane;

/**
 *
 * @author MiguelAspire5
 */
public class TelaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        molduraInterna = new javax.swing.JInternalFrame();
        panelTela = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        HAL9000 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCadastro = new javax.swing.JMenu();
        menCliente = new javax.swing.JMenuItem();
        menOS = new javax.swing.JMenuItem();
        menUsuario = new javax.swing.JMenuItem();
        menRelatorio = new javax.swing.JMenu();
        menSobre = new javax.swing.JMenu();
        menSair = new javax.swing.JMenu();
        menSair2 = new javax.swing.JMenuItem();

        molduraInterna.setClosable(true);
        molduraInterna.setIconifiable(true);
        molduraInterna.setMaximizable(true);
        molduraInterna.setResizable(true);
        molduraInterna.setTitle("Sistema para gestão de serviços - Ver. 1.3");
        molduraInterna.setVisible(true);

        panelTela.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelTelaLayout = new javax.swing.GroupLayout(panelTela);
        panelTela.setLayout(panelTelaLayout);
        panelTelaLayout.setHorizontalGroup(
            panelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        panelTelaLayout.setVerticalGroup(
            panelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Usuário:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblUsuario.setText("USUÁRIO");

        jLabel3.setText("Data:");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblData.setText("DATA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblData))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        HAL9000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/HAL9000NETBEANS256.png"))); // NOI18N
        HAL9000.setMaximumSize(new java.awt.Dimension(256, 256));

        menCadastro.setText("Cadastro");
        menCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroActionPerformed(evt);
            }
        });

        menCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCliente.setText("Cliente");
        menCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienteActionPerformed(evt);
            }
        });
        menCadastro.add(menCliente);

        menOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menOS.setText("OS");
        menCadastro.add(menOS);

        menUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menUsuario.setText("Usuários");
        menUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menUsuarioActionPerformed(evt);
            }
        });
        menCadastro.add(menUsuario);

        jMenuBar1.add(menCadastro);

        menRelatorio.setText("Relatório");
        jMenuBar1.add(menRelatorio);

        menSobre.setText("Sobre");
        jMenuBar1.add(menSobre);

        menSair.setText("Sair");

        menSair2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menSair2.setText("Sair");
        menSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSair2ActionPerformed(evt);
            }
        });
        menSair.add(menSair2);

        jMenuBar1.add(menSair);

        molduraInterna.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout molduraInternaLayout = new javax.swing.GroupLayout(molduraInterna.getContentPane());
        molduraInterna.getContentPane().setLayout(molduraInternaLayout);
        molduraInternaLayout.setHorizontalGroup(
            molduraInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(molduraInternaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(molduraInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(molduraInternaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(HAL9000, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        molduraInternaLayout.setVerticalGroup(
            molduraInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, molduraInternaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(molduraInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(molduraInternaLayout.createSequentialGroup()
                        .addComponent(HAL9000, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(molduraInterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(molduraInterna)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menClienteActionPerformed

    private void menSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSair2ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null,"Deseja sair do programa?","Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menSair2ActionPerformed

    private void menCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroActionPerformed
        
    }//GEN-LAST:event_menCadastroActionPerformed

    private void menUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUsuarioActionPerformed
        TelaUsuario usuario= new TelaUsuario();
        usuario.setVisible(true);
        panelTela.add(usuario);
    }//GEN-LAST:event_menUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HAL9000;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menCadastro;
    private javax.swing.JMenuItem menCliente;
    private javax.swing.JMenuItem menOS;
    private javax.swing.JMenu menRelatorio;
    private javax.swing.JMenu menSair;
    private javax.swing.JMenuItem menSair2;
    private javax.swing.JMenu menSobre;
    private javax.swing.JMenuItem menUsuario;
    private javax.swing.JInternalFrame molduraInterna;
    private javax.swing.JPanel panelTela;
    // End of variables declaration//GEN-END:variables
}
